### ISSUE TITLE
'dict object' has no attribute 'stdout' 

### ISSUE THREAD

**Issue by IvanJobs** [ansible-collections/ansible-consul#24] opened 2017-02-16 07:32 UTC
I'm new to this project and just trying it now.  errors come out from a few of my servers.

my inventory file:
```
[cluster_nodes]
adcb-zk-1.vm.elenet.me consul_node_role=bootstrap
adcb-zk-[2:3].vm.elenet.me consul_node_role=server
adcb-mesos-[18:23].vm.elenet.me consul_node_role=client
```

my playbook:
```
---
- name: Assemble Consul cluster
  hosts: cluster_nodes 
  remote_user: root 
  roles:
    - { role: brianshumate.consul }
```

error log:
```
TASK [brianshumate.consul : Save encryption key] *******************************
skipping: [adcb-mesos-18.vm.elenet.me] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
fatal: [adcb-mesos-18.vm.elenet.me]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/etc/ansible/roles/brianshumate.consul/tasks/main.yml': line 89, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      run_once: true\n    - name: Save encryption key\n      ^ here\n"}
```

my starting code:
```
ansible-playbook -i ./hosts consul.yml --extra-vars "consul_iface={{ansible_default_ipv4.alias}}" -v
```
any help would be appreciated :)

**Comment by IvanJobs** [comment] 2017-02-16 08:01
BTW, is there any way to roll back this playbook?

**Comment by brianshumate** [comment] 2017-02-16 14:45
Thanks for the report; this is an odd issue and I'll look into it. There is no rollback mechanism in this role.

**Comment by brianshumate** [comment] 2017-02-20 19:26
Hi,

Can you try this again with the latest version (1.9.0) and let me know if you still see the error?

Thanks!

**Comment by IvanJobs** [comment] 2017-02-23 07:11
@brianshumate  ok, I will try it later.

**Comment by IvanJobs** [comment] 2017-02-23 07:46
@brianshumate 
It may be not correct but I download 1.9.0 from release tab in this repo, and substitute content in /etc/ansible/role/brianshumate.consul/*, rerun playbook, error still occurs:

> TASK [brianshumate.consul : Save encryption key] *******************************
skipping: [adcb-zk-2.vm.elenet.me]
skipping: [adcb-zk-3.vm.elenet.me]
skipping: [adcb-zk-1.vm.elenet.me]
fatal: [adcb-mesos-19.vm.elenet.me]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/etc/ansible/roles/brianshumate.consul/tasks/main.yml': line 90, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Save encryption key\n      ^ here\n"}
fatal: [adcb-mesos-18.vm.elenet.me]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/etc/ansible/roles/brianshumate.consul/tasks/main.yml': line 90, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Save encryption key\n      ^ here\n"}
fatal: [adcb-mesos-20.vm.elenet.me]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/etc/ansible/roles/brianshumate.consul/tasks/main.yml': line 90, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Save encryption key\n      ^ here\n"} 

In the meantime, I found something weird that may be some help.
all error hosts share common network config with "ip a" like below:

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master dockermesos state UP qlen 1000
    link/ether 00:16:3e:1a:2a:9b brd ff:ff:ff:ff:ff:ff
3: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether 26:6f:de:f1:4a:d5 brd ff:ff:ff:ff:ff:ff
    inet 10.2.137.32/15 scope global flannel.1
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 02:42:0d:b3:f5:0e brd ff:ff:ff:ff:ff:ff
    inet 10.2.137.33/28 scope global docker0
       valid_lft forever preferred_lft forever
5: dockermesos: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 00:16:3e:1a:2a:9b brd ff:ff:ff:ff:ff:ff
    inet 10.101.117.212/19 brd 10.101.127.255 scope global dockermesos
       valid_lft forever preferred_lft forever

In a quick review, we create a bridge named dockermesos using eth0's IP, and eth0 as a interface binding to bridge dockermesos. Maybe interface name isn't eth0 would cause problem in this role, I don't know, but just a clue for u.

**Comment by IvanJobs** [comment] 2017-02-23 08:29
I just tried again with several new provisioned servers, there is no error. It seems related to our network cfgs. Even so, this role's error msg confused me :(

**Comment by brianshumate** [comment] 2017-02-23 14:23
That's quite odd indeed since the error indicates a part of the play that is calling `consul keygen` and attempting to save the resulting gossip encryption key; it should not involve network interfaces.

There is a `consul_iface` variable that you can set to control the interface name. It's also settable by an environment variable `CONSUL_IFACE`. I need to document the variables a little better.

Glad you got it working. I'll go ahead and close this now since I can't reproduce it in my test environments.

**Closed as completed by brianshumate** 2017-02-23 14:23 UTC
